ingestion_tools/dataset_configs/10002.yaml
ingestion_tools/dataset_configs/10004.yaml
ingestion_tools/dataset_configs/10010.yaml
ingestion_tools/scripts/common/normalize_fields.py
ingestion_tools/scripts/db_import.py
ingestion_tools/scripts/gjensen_config.py
ingestion_tools/scripts/importers/tomogram.py

This should prevent us from winding up with `true/false/FIDUCIAL/NON_FIDUCIAL` values in our db when our metadata schema specifically calls for the only valid values to be `FIDUCIAL` and `NON_FIDUCIAL`.
Once this is merged I'll update the DB as well.

Normalize values for fiducial_alignment_status

---

.github/workflows/staging-deploy.yaml
.gitignore
.happy/terraform/envs/dev/main.tf
.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/staging/main.tf

Adds workflow to deploy to staging on merge to main for api
Depends on: https://github.com/chanzuckerberg/cryoet-infra/pull/85

Setting up staging deploy worklfow

---

.happy/terraform/envs/dev/main.tf
.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/staging/main.tf

- Moving `platform_architecture` into service
- Adding `app_name` to happy-stack-eks  to resolve errors arising from invalid naming convention of `spec.template.spec.containers[..].envFrom[..].secretRef.name` (Change introduced in [happy-service-eks-v3.21.0](https://github.com/chanzuckerberg/happy/releases/tag/happy-service-eks-v3.21.0))

Updating tf to match new spec

---

docker-compose.yml

These fixes build errors for the GitHub workflow as we are using `ARM64` for it. 
Update infra for batch workflow to also use `arm64`.

Updaing ingestor image to arm platform

---

ingestion_tools/scripts/common/image.py
ingestion_tools/scripts/importers/annotation.py

Fixing https://github.com/chanzuckerberg/cryoet-data-portal/issues/502
1. The labels in segmentation masks were not correctly separated because `pyramid_to_mrc` in `common/image.py` took the original data, not the one from the pyramid (only the pyramid data is processed)
2. AnnotationSource classes in `importers/annotation.py` expected the keyword argument `is_viz_default`, but the YAML dict has `is_visualization_default`
3.  Import of `Point` annotations failed due to faulty indenting in `Point.load` in `importers/annotation.py`
4. Voxel spacing of the ingested segmentation masks was not correct, because `scale_maskfile` in `common/image.py` was not yet using the new override mechanism for the `voxel_spacing` (the correct `voxel_spacing` was actually passed inside …

Fix ingestion of segmentation masks

---

ingestion_tools/dataset_configs/template.yaml
ingestion_tools/scripts/common/config.py

Adds a default value of `None` for all optional standard config fields.

fix: Adding default values for optional fields

---

ingestion_tools/scripts/common/image.py

After the initial comparison with the label the maps are already binary, so after the scaling operation we need to compare with 1 instead of comparing with the label again. 
Scaled masks are binary and should be stored as int8.
This PR fixes that.

Fix downscaling and data type of segmentation masks

---

ingestion_tools/dataset_configs/10002.yaml

Masks in 10002 were still imported using the old "SegmentationMask" type instead of the "SemanticSegmentationMask". 
Changed to the appropriate annotation type with this PR.

Fix annotation type for segmentation masks in 10002

---

ingestion_tools/scripts/common/instance_point_converter.py
ingestion_tools/scripts/importers/annotation.py

Imports TARDIS instance points, new point formate with the additional label "instance_id".

Add Annotation Importer for Instance segmentations. 

---

api_server/metadata/databases/cryoetdataportal/tables/public_annotations.yaml
api_server/metadata/databases/cryoetdataportal/tables/public_tomograms.yaml
api_server/migrations/cryoetdataportal/1711382347768_alter_table_public_annotations_add_column_method_type/down.sql
api_server/migrations/cryoetdataportal/1711382347768_alter_table_public_annotations_add_column_method_type/up.sql
api_server/migrations/cryoetdataportal/1711382362955_alter_table_public_annotations_add_column_deposition_id/down.sql
api_server/migrations/cryoetdataportal/1711382362955_alter_table_public_annotations_add_column_deposition_id/up.sql
api_server/migrations/cryoetdataportal/1711382818512_alter_table_public_tomograms_add_column_deposition_id/down.sql
api_server/migrations/cryoetdataportal/1711382818512_alter_table_public_tomograms_add_column_deposition_id/up.sql

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/443, https://github.com/chanzuckerberg/cryoet-data-portal/issues/542
- Adds `method_type` field to the annotations table
- Adds `deposition_id` field to the annotations table
- Adds `deposition_id` field to the tomograms table

feat: Adding new fields to db

---

.github/workflows/prod-deploy.yaml

Adds GitHub workflow to deploy GraphQL to prod environment.

feat: Add graphql prod deploy workflow

---

ingestion_tools/scripts/importers/neuroglancer.py

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/622
- Updates the dimensions for the neuroglancer scale with voxel spacing
- Adds center of the volume as the focus point of the neuroglancer on load
- Updates zoom for the cross sections to fit the longest dimension of the volume
- Sets the cross-section background to black for a better user experience 
[Link 1](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B2.164e-9%2C%22m%22%5D%2C%22y%22:%5B2.164e-9%2C%22m%22%5D%2C%22z%22:%5B2.164e-9%2C%22m%22%5D%7D%2C%22position%22:%5B480%2C464%2C64%5D%2C%22crossSectionScale%22:2.4%2C%22projectionScale%22:1009.4543247609109%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://https://files.cryoetdataportal.cziscience.com/10027/wnj2019-02-2 …

fix: Updating neuroglancer config with dimensions

---

ingestion_tools/scripts/common/db_models.py
ingestion_tools/scripts/importers/db/annotation.py
ingestion_tools/scripts/importers/db/tomogram.py
ingestion_tools/scripts/tests/db_import/test_db_annotation_import.py
ingestion_tools/scripts/tests/db_import/test_db_tomo_import.py
test_infra/sql/schema.sql
test_infra/test_files/30001/RUN1/Tomograms/VoxelSpacing12.300/Annotations/100-foo-1.0.json
test_infra/test_files/30001/RUN2/Tomograms/VoxelSpacing3.456/CanonicalTomogram/tomogram_metadata.json

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/542, https://github.com/chanzuckerberg/cryoet-data-portal/issues/443
Adds db import support for deposition_id and method_type, and updates the relevant tests.

feat: Adding db_import support for new fields

---

ingestion_tools/dataset_configs/10301.yaml
ingestion_tools/scripts/tomoman_to_tsv.py

1. Ingestion config for 10301 including metadata and all available annotations. 
2. A short script extracting metadata referenced in the ingestion config from the tomoman `.mat` file and writing them to a run to data map tsv
Run the script as 
`tomoman_to_tsv.py convert PATH/TO/tomolist.mat PATH/TO/run_to_data_map.tsv`
Both files live on S3.

Ingestion config for 10301 and tomoman mat-file to map-tsv conversion tool

---

ingestion_tools/scripts/common/make_key_image.py
ingestion_tools/scripts/importers/key_image.py

Updates to handle when an annotation file doesn't exist for specific annotation spec.

fix: Updating key image generation when no annotation exists

---

.pre-commit-config.yaml
api_server/metadata/databases/cryoetdataportal/tables/public_annotation_authors.yaml
api_server/migrations/cryoetdataportal/1712956764128_alter_table_public_annotation_authors_add_column_primary_author_status/down.sql
api_server/migrations/cryoetdataportal/1712956764128_alter_table_public_annotation_authors_add_column_primary_author_status/up.sql
ingestion_tools/Dockerfile
ingestion_tools/pyproject.toml
ingestion_tools/scripts/common/db_models.py
ingestion_tools/scripts/importers/db/annotation.py
ingestion_tools/scripts/tests/db_import/test_db_annotation_import.py
test_infra/sql/schema.sql
test_infra/sql/seed_db_data.sql

This field is set up to have the exact same data as `annotation_authors.primary_annotation_status` so we can add the new field, get clients updated to use it, and then deprecate the old one.

chore: Make a new `annotation_authors.primary_author_status` field

---

ingestion_tools/scripts/common/image.py
ingestion_tools/scripts/importers/annotation.py
ingestion_tools/scripts/standardize_dirs.py

- Refactors code to unify scale_mrcfile and scale_maskfile by adding `label` parameter to scale_mrcfile. 
- Simplifies `MaskConverter` by making the `TomoConverter` more extensible
- Adds write_mrc and write_zarr flag implementation to annotations

Minor refactor of Annotation to improve code reuse

---

.github/workflows/push-ingestor-build.yaml
Makefile

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/363
- Adds make target to build and push to remote repo
- Introduces github workflow to build and push ingestor image to remote when changes are merged to main.

Adding github workflow to build and push ingestor image

---

.happy/terraform/envs/prod/main.tf

Increases the desired number of servers for the graphql api in prod from 1 -> 2. This would help create redundancies for the production of the API service. 
Increases the max count for the graphql api in prod from 2 -> 5. Allows the application to scale to up to 5 instances.

Increasing prod service count

---

Makefile
api_server/migrations/cryoetdataportal/1717093534072_create_index_annotations_deposition_id/down.sql
api_server/migrations/cryoetdataportal/1717093534072_create_index_annotations_deposition_id/up.sql
api_server/migrations/cryoetdataportal/1717093573267_create_index_tomograms_deposition_id/down.sql
api_server/migrations/cryoetdataportal/1717093573267_create_index_tomograms_deposition_id/up.sql

Adds a btree index on the `deposition_id` column of `annotations` and `tomograms` table. This helps optimize for querying on the deposition_id on those tables.

feat: Adding index on deposition_id columns

---

ingestion_tools/scripts/common/image.py

Removes `n` in the `{d}start` attr name VolumeInfo get_dimensions.

Updating VolumeInfo get_dimensions

---

ingestion_tools/scripts/common/point_converter.py
ingestion_tools/scripts/tests/s3_import/test_annotations_import.py

During refactor, `xyz_rotation_matrix` in orientedPoint was renamed to `rotation_matrix`. 
Revert to `xyz_rotation_matrix` for compatibility.

Minor fix of orientedPoint import

---

api_server/Dockerfile
ingestion_tools/Dockerfile

For https://github.com/chanzuckerberg/cryoet-data-portal/issues/777, updates the TLS certificates in docker containers that need DB access.

Install new TLS roots for RDS db's.

---

ingestion_tools/dataset_configs/10301.yaml

Updates the glob for the `F1-F0-ATPase complex` as it currently also matches against files for `mitochondrial F1-F0-ATPase complex`.

fix: Fixing ds10301 annotion glob

---

ingestion_tools/scripts/common/finders.py
ingestion_tools/scripts/tests/s3_import/test_finders.py

Fixes: https://github.com/chanzuckerberg/cryoet-data-portal/issues/842
This fixes the broken logic for include/exclude filters in ingestion configs. Basically it updates the logic so that if *any* exclude filter for *any* parent object is triggered, the object import will be canceled, and *at least one* of the include filters for each of the parent filters must match for the import to proceed.

fix: Fix finders and add test coverage for them.

---

ingestion_tools/scripts/dataset_config_merge.py

Now, when you run `python dataset_config_merge.py`, you can specify the `--unique_values` flag to get all unique values from the config files in the dataset_configs/ folder. Helpful when wondering what the current data looks like for a specific field.

Add ability to store all unique values when using dataset_config_merge.py

---

ingestion_tools/scripts/common/metadata.py

Because the version could be a number / float (it currently is, as defined by the template.yaml), we should typecast the variable to a string before calling `lower`. Makes the code more robust and support version numbers that are both strings and numbers.

Fix ingestion / importer annotation version bug

---

ingestion_tools/scripts/common/image.py

Relates to
#166
The property `MrcObject.extended_header` may return `None`, or values of type `np.recarray` or `np.ndarray`. In contrast to python lists, `np.ndarray` is not truthy, so comparison with any `np.ndarray` will raise exceptions. In order to circumvent, we ensure that the result of `MRCReader.get_mrc_extended_header()` is a np.array and then convert to a python list that enables truthy/falsy comparison. 
Covers the following cases: 
1. do set extended header on filled `np.ndarray` > `np.array(val: np.ndarray).tolist() -> list`
2. do set extended header on filled `np.recarray` > `np.array(val: np.recarray).tolist() -> list`
3. skip setting extended header on empty `np.ndarray` > `np.array(np.empty(0)).tolist() == []`
4. skip setting extended header on `None` > …

Fix setting extended header when importing MRC

---

schema/v1.1.0/dataset_config_models_extended.py

Currently, we do case-insensitive checking of ontology object names in the dataset config (against the values stored online by databases). Because capitalization does actually matter for some ontology object names, we switch to case-sensitive checking. Ontology object IDs remain case-sensitive checks.

Dataset config validation: make ontology object & exclusion list checking case sensitive

---

ingestion_tools/scripts/common/image.py
ingestion_tools/scripts/importers/annotation.py

Relates to
Fixes the issue of segmentation mask output being a float. The [converter selection](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/66e0ddc0cffdafe8b0d71d678b7443a585337ca2/ingestion_tools/scripts/common/image.py#L418) is determined by if the label is `None`.

fix: Segmentation mask output datatype to int

---

ingestion_tools/dataset_configs/10436.yaml
ingestion_tools/dataset_configs/10436_draft.yaml
ingestion_tools/dataset_configs/10437.yaml
ingestion_tools/dataset_configs/10437_draft.yaml
ingestion_tools/dataset_configs/10438.yaml
ingestion_tools/dataset_configs/10438_draft.yaml
schema/v1.1.0/dataset_config_validation_exclusions.json

This PR adds the full config files for Datasets 10436, 10437, 10438 ([preprint](https://www.biorxiv.org/content/10.1101/2024.07.13.603322v1))

Full config files for deposition 10307 (Datasets 10436, 10437, 10438)

---

api_server/metadata/databases/cryoetdataportal/tables/public_depositions.yaml
api_server/migrations/cryoetdataportal/1723167977727_alter_table_public_depositions_add_column_key_photo_url/down.sql
api_server/migrations/cryoetdataportal/1723167977727_alter_table_public_depositions_add_column_key_photo_url/up.sql
ingestion_tools/scripts/common/db_models.py
ingestion_tools/scripts/common/formats.py
ingestion_tools/scripts/tests/db_import/conftest.py
ingestion_tools/scripts/tests/db_import/test_db_annotation_import.py
ingestion_tools/scripts/tests/db_import/test_db_deposition_import.py
test_infra/sql/schema.sql

- Adds relationship between deposition and datasets, annotation, tiltseries and tomograms
- Adds fix to prevent the method links from getting string encoded twice
- Adds key photo urls to depositions

Adding relationship from deposition entity

---

schema/core/v1.1.0/codegen/metadata_materialized.yaml
schema/core/v1.1.0/codegen/metadata_models.py
schema/core/v1.1.0/metadata.yaml
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json
schema/ingestion_config/v1.0.0/ingestion_config_models.yaml
schema/schema.py

The schema.py script was quite difficult to understand with all of the messy patches to get the schema files materialized correctly. This PR cleans it up and also creates better rendered materialized file (with more of the fields / attributes properly carried over). It might be easier to read the schema.py without the diff, because there are some quite big refactors (but functionality more or less remains the same, with some non-breaking improvements).
This PR also fixes some metadata.yaml bugs and resolves some TODOs that weren't actually blocked.

Schema.py refactor & bug fixes

---

schema/Makefile
schema/api/v2.0.0/api_models.yaml
schema/api/v2.0.0/codegen/api_models_materialized.yaml
schema/core/v2.0.0/codegen/metadata_materialized.yaml
schema/core/v2.0.0/common.yaml
schema/core/v2.0.0/metadata.yaml

This is a draft of the schema changes that are coming for the v2 api

DRAFT: proposed changes for v2 schema

---

ingestion_tools/dataset_configs/template.yaml

A template.yaml indentation fix (parent_filters is not a child of sources children, but a source child in itself to be paired along with other sources children)

fix parent filters indentation

---

.pre-commit-config.yaml
ingestion_tools/scripts/dataset_config_merge.py
ingestion_tools/scripts/tests/s3_import/test_deposition.py

he pre-commit hooks are failing because some files were merge without pre-commit enabled. 
- Apply pre-commit hooks to all files in the repository.

chore: apply pre-commit hooks

---

ingestion_tools/dataset_configs/template.yaml
schema/api/v1.0.0/codegen/api_models_materialized.yaml
schema/api/v2.0.0/codegen/api_models_materialized.yaml
schema/core/v1.1.0/codegen/metadata_materialized.yaml
schema/core/v1.1.0/codegen/metadata_models.py
schema/core/v1.1.0/common.yaml
schema/core/v2.0.0/codegen/metadata_materialized.yaml
schema/core/v2.0.0/common.yaml
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml
schema/ingestion_config/v1.0.0/ingestion_config_models_extended.py

- Fix annotation publications list description (include PDB) and also have "PDB-" prefix, not "pdb" prefix
- Add "SIMULATED" option to microscope manufacturer enum
- Add UniProtKB id support to dataset.annotation_object.id
- Change `default_range` of v2.0.0 common.yaml schema to Any, so that `range` / type values of slots are properly written.

Schema features & fixes: annotation object id UniProtKB support, annotation publications, microscope manufacturer enum

---

api_server/migrations/cryoetdataportal/1724881704024_alter_table_public_annotations_object_id_comment/down.sql
api_server/migrations/cryoetdataportal/1724881704024_alter_table_public_annotations_object_id_comment/up.sql

Follows up on supporting UniProtKB (which was done here https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/213)
Question: how do I actually get the migration run?

Rename db comment for annotation object_id 

---

.github/workflows/docker-build-staging-prod.yaml
apiv2/README.md

chore: build a staging docker image

---

ingestion_tools/poetry.lock
ingestion_tools/scripts/data_validation/conftest.py
ingestion_tools/scripts/data_validation/fixtures/data.py
ingestion_tools/scripts/data_validation/fixtures/path.py
ingestion_tools/scripts/data_validation/tests/test_tilt_angles.py

Merge after #223.
See the Tilts & RawTilts & Angles Cross Checks section of https://docs.google.com/document/d/1yMKM0DW9KRhlcYiBGPcR7oW0liGtUew6NAmBhMg5U3w/edit.
Documentation from the code: 
```
"""
A class to test tilt angle data. Only checking that the # of angles in these files are consistent with other files / 
data and that they properly map to other files / data. Other data validation tests is done in respective classes.
Spans .tlt, .rawtlt, .mdoc, tiltseries_metadata.json, frames files.
Ordering:
- .tlt (<=) maps to .rawtlt (not necessarily 1:1)
- .rawtlt (<=) maps to .mdoc (not necessarily 1:1)
- .mdoc (==) one-to-one with frames files & tiltseries_metadata size["z"]
- tiltseries metadata size["z"] == frames_count == # of frames files
Extra test redundancy is added for the cases …
```

feat: s3 data validation: cross checking tiltseries & frames files 

---

ingestion_tools/dataset_configs/10010.yaml
schema/ingestion_config/v1.0.0/ingestion_config_models_extended.py

The rawtilts entry for 10010.yaml was also failing (the list_globs array must have at least one element if it exists), so i just commented it out. We can also remove it, if that seems fit.

add extended validation check for collection metadata

---

.gitattributes

Reviewing code with lots of generated code is time consuming. To make that process easier, generated files in the schema and poetry will be hidden in the Pull request and will need to be manually expanded to view.

fix: hide generated schema and poetry files in PRs

---

ingestion_tools/scripts/enqueue_runs.py

Relates to
Fixing a typo in the prefix for depositions metadata sync.

fix: Correct prefix for deposition sync in enqueue_runs.py

---

apiv2/platformics/graphql_api/core/query_input_types.py

The Frrontend team noticed that query filters for boolean values were erroneously requiring integer values as input. This updates the GraphQL interface to require bools as input instead. I also removed the comparisons (gt, lt) that looked irrelevant to boolean comparisons

fix: make sure bool comparators don't require int input.

---

apiv2/main.py
apiv2/platformics/database/connect.py
apiv2/platformics/graphql_api/core/strawberry_extensions.py
apiv2/poetry.lock
apiv2/pyproject.toml

This fixes two major bugs in apiv2:
1. The api was creating a new database connection pool on every request, which basically meant that we had no limit on the number of db connections between the app and the database. We're now creating the pool once at the startup of the app, and then fetching connections from that pool in the rest of the app. I've currently set the limit at 5 connections (which can burst up to 10 connections) per worker. Each pod has 4 workers, and we have two pods running in most environments, which means a max of 80 connections possible from the api, while the limit at the database server is around 200 connections, so we should be in good shape for awhile.
2. We weren't properly closing database sessions due to the way we were handling our integration with FastAPI's …

fix: Make sure we're using DB connection pools properly.

---

ingestion_tools/dataset_configs/10000.yaml
ingestion_tools/dataset_configs/10001.yaml
ingestion_tools/dataset_configs/10002.yaml
ingestion_tools/dataset_configs/10003.yaml
ingestion_tools/dataset_configs/10004.yaml
ingestion_tools/dataset_configs/10005.yaml
ingestion_tools/dataset_configs/10006.yaml
ingestion_tools/dataset_configs/10007.yaml
ingestion_tools/dataset_configs/10008.yaml
ingestion_tools/dataset_configs/10009.yaml
ingestion_tools/dataset_configs/10010.yaml
ingestion_tools/dataset_configs/10011_draft.yaml
ingestion_tools/scripts/tests/fixtures/annotations/anno_config.yaml
ingestion_tools/scripts/tests/fixtures/dataset1.yaml
ingestion_tools/scripts/tests/fixtures/voxel_spacing/mrc_header.yaml
ingestion_tools/scripts/tests/fixtures/voxel_spacing/overrides_by_run.yaml
ingestion_tools/scripts/tests/fixtures/voxel_spacing/tomo_metadata.yaml
ingestion_tools/scripts/tests/fixtures/voxel_spacing/tomo_run_data_map.yaml

Relates to
Fixing the values for the key images literal to valid photo key names.
In the past, the config's incorrect literal values were being overwritten with correct values. But, that has been replaced with adding the source only if a config doesn't already contain an entry for the entity. 
Removing the incorrect values will default to adding the correct values in the config.

fix: Fixing the values for key photo literals

---

ingestion_tools/scripts/gjensen_config.py
ingestion_tools/scripts/schema_migration/__main__.py
ingestion_tools/scripts/schema_migration/transform_ingestion_configs.py
ingestion_tools/scripts/transform_ingestion_configs.py

- Add a docstring and description for the upgrade command
- Update transform_ingestion_configs to be extended to support upgrading an ingest config from version 0.0.0 and beyond.
- move schema migrations code to ingest_tools/schema_migration
- update gjensen_config.py to run with reorganization.
- related to #262 
Test manually by modifying an existing ingest config to a previous version.

feat: transform_ingestion_configs.py support multiple versions

---

ingestion_tools/scripts/tests/db_import/conftest.py
ingestion_tools/scripts/tests/db_import/test_db_tiltseries_import.py
ingestion_tools/scripts/tests/db_import/test_db_tomo_import.py

This fixes an issues causing the make recipe `ingestor-test-db`
Something from this  [PR](https://github.com/chanzuckerberg/cryoet-data-portal-backend/commit/f04e5f3df2482f8d8a630628cd8154f3e487a99) broke the ingest-db tests. It's associated with some of the test infra files like test_infra/test_files/30001/dataset_metadata.json. Here is the [run](https://github.com/chanzuckerberg/cryoet-data-portal-backend/actions/runs/11061158693/job/30733496664?pr=262) in my PR after merging in main.

chore: fix failing tests in ingestor-test-db cases for api v2

---

apiv2/Makefile

Docker compose has had a [variety of issues](https://github.com/docker/compose/issues?q=is%3Aissue+run+recreates) (spanning several years!) with recreating containers in situations where it shouldn't, especially when executing `docker compose run`. I've had problems launching the apiv2 dev environment in some cases, where `make alembic-upgrade` will erroneously tear down the db container and recreate it from scratch, but since we're reliant on an additional DB being added to postgres before running alembic upgrades, this db container recreate causes the startup of the dev environment to fail. Adding this `--no-deps` flag seems to fix the problem on my laptop, so I'm hoping it doesn't break anything in CI.

fix: workaround for docker compose bugs.

---

.gitignore
apiv2/graphql_api/types/alignment.py
apiv2/graphql_api/types/annotation.py
apiv2/graphql_api/types/annotation_author.py
apiv2/graphql_api/types/annotation_file.py
apiv2/graphql_api/types/annotation_shape.py
apiv2/graphql_api/types/dataset.py
apiv2/graphql_api/types/dataset_author.py
apiv2/graphql_api/types/dataset_funding.py
apiv2/graphql_api/types/deposition_author.py
apiv2/graphql_api/types/deposition_type.py
apiv2/graphql_api/types/frame.py
apiv2/graphql_api/types/per_section_alignment_parameters.py
apiv2/graphql_api/types/per_section_parameters.py
apiv2/graphql_api/types/run.py
apiv2/graphql_api/types/tiltseries.py
apiv2/graphql_api/types/tomogram.py
apiv2/graphql_api/types/tomogram_author.py
apiv2/graphql_api/types/tomogram_voxel_spacing.py
apiv2/platformics/codegen/lib/linkml_wrappers.py
apiv2/template_overrides/graphql_api/types/class_name.py.j2

This PR does a couple things:
1. It removes `lib` from `.gitignore` since this was preventing us from checkin in an important file!
2. Adds that important file to the repo, kindof belatedly.
3. Updates codegen to add `some_related_class_id` fields to where clauses so they can be filtered. This functionality is necessary to support the client!

fix: support filtering entities by related object id's

---

apiv2/scripts/seed.py

This is the start of a script that can seed our local dev environment with test data. It's not wired into anything right now, but it may be useful in the future for CI. It's basically a translation of [this script](https://github.com/chanzuckerberg/cryoet-data-portal/blob/main/client/python/cryoet_data_portal/tests/test_infra/hasura/migrations/cryoetdataportal/0000000000001_data/up.sql) to `factory_boy` with a few updates for our new schema (to support `alignments` and `annotation_shape` etc)

chore: add seed script.

---

ingestion_tools/dataset_configs/10000.yaml
ingestion_tools/dataset_configs/10001.yaml
ingestion_tools/dataset_configs/10002.yaml
ingestion_tools/dataset_configs/10004.yaml
ingestion_tools/dataset_configs/10008.yaml
ingestion_tools/dataset_configs/10009.yaml
ingestion_tools/dataset_configs/10301.yaml
ingestion_tools/dataset_configs/10302.yaml
ingestion_tools/dataset_configs/10436.yaml
ingestion_tools/dataset_configs/10437.yaml
ingestion_tools/dataset_configs/10439.yaml
ingestion_tools/dataset_configs/template.yaml
ingestion_tools/scripts/importers/alignment.py
ingestion_tools/scripts/schema_migration/migrate_v1_1_0.py
ingestion_tools/scripts/schema_migration/upgrade.py
ingestion_tools/scripts/tests/fixtures/dataset1.yaml
ingestion_tools/scripts/tests/s3_import/test_alignments.py
schema/core/v1.1.0/codegen/metadata_materialized.yaml
schema/core/v1.1.0/codegen/metadata_models.py
schema/core/v1.1.0/common.yaml
schema/core/v1.1.0/metadata.yaml
schema/core/v2.0.0/metadata.yaml
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml

Relates to
- Updates the `is_canonical` -> `is_portal_standard`
- Adds the `method_type`
- Updates the spelling of volume_dimension
- Adds migration handler for `alignment.method_type` in the config. It follows the following conditions:
```
Everything that is FIDUCIAL is fiducial_based
Everything that mentions AreTomo as reconstruction software is projection matching
If reconstruction_software=IMOD and NON_FIDUCIAL is patch_tracking
Else undefined
```
- Removes trailling whitespaces in the configs
- Adds "files" field to the alignment metadata. This lists all the files associated to this alignment
- Adds `get_name_and_path` class method to the AlignmentImporter. This allows the DestinationFilterFinder to reference an existing Alignment.

feat: Updates to the alignment entity

---

release-please-config.json

This just adds a link to the APIv2 deployment doc to the footer of PR's created by the `release-please` action.
The docs for this feature are here: https://github.com/googleapis/release-please/blob/main/docs/customizing.md#pull-request-footer

chore: Update footer of release please PR's.

---

.infra/prod/Chart.yaml
.infra/rdev/Chart.yaml
.infra/staging/Chart.yaml

https://czi.atlassian.net/browse/CCIE-3465
Upgrade argus helm chart to make way for LetsEncrypt TLS certificates

chore: upate the argus stack helm chart

---

ingestion_tools/scripts/common/finders.py

This fixes a bug for DestinationFinder.
Updates the metadata used by MultiSourceFileFinder to the remote metadata that lives in s3, instead of the metadata from ingestion config file.

fix: Update metadata fetch for MultiSourceFileFinder

---

ingestion_tools/scripts/common/config.py
ingestion_tools/scripts/common/exceptions.py
ingestion_tools/scripts/common/image.py
ingestion_tools/scripts/importers/alignment.py
ingestion_tools/scripts/importers/annotation.py
ingestion_tools/scripts/importers/base_importer.py
ingestion_tools/scripts/importers/run.py
ingestion_tools/scripts/importers/tomogram.py
ingestion_tools/scripts/tests/s3_import/test_alignments.py
ingestion_tools/scripts/tests/s3_import/test_tiltseries.py
ingestion_tools/scripts/tests/s3_import/test_tomograms.py

Relates to
Updates all the paths specified in the metadata to follow the same pattern. 
The paths for `tiltseries_path`, `alignment_path`, `tilt_path`, `tiltx_path`, `files` no longer specify the bucket.
- The paths for `omezarr_dir`, `mrc_file` are the complete path instead of just the file name
- The `mrc_files` property is renamed to `mrc_file`, and the value of a single element list is now just a string.
- The paths for `omezarr_dir`, `mrc_file` are the complete path instead of just the file name
- The `mrc_files` property is renamed to `mrc_file`, and the value of a single element list is now just a string.
- The `alignment_metadata_path` and `neuroglancer_config_path` no longer specifies the bucket name.

feat: Standardizing paths in metadata

---

ingestion_tools/scripts/importers/key_image.py
ingestion_tools/scripts/tests/s3_import/test_tomograms.py

Relates to
Migrates `{dataset_name}/{run_name}/Reconstructions/VoxelSpacing{voxel_spacing_name}/Images/{tomogram_id}-key-photo-{image_type}.png` -> `{dataset_name}/{run_name}/Reconstructions/VoxelSpacing{voxel_spacing_name}/Images/{tomogram_id}/key-photo-{image_type}.png`

fix: Updating the tomogram key photo path

---

ingestion_tools/poetry.lock
ingestion_tools/pyproject.toml
ingestion_tools/scripts/common/alignment_converter.py
ingestion_tools/scripts/tests/fixtures/alignments/alignment3.yaml
ingestion_tools/scripts/tests/fixtures/alignments/alignment4.yaml
ingestion_tools/scripts/tests/fixtures/dataset2.yaml
ingestion_tools/scripts/tests/s3_import/test_alignments.py
test_infra/test_files/input_bucket/10001_input/alignments/TS_run1.aln

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1208
Adds conversion for IMOD and AreTomo3 alignments to the AlignmentConverter class. This is based on the alignment conversions in [cryoet-alignment](https://pypi.org/project/cryoet-alignment/0.0.5/).

feat: Add alignment conversion for IMOD and AreTomo3

---

ingestion_tools/scripts/common/config.py

Relates to
Only updates the path if the output prefix is in it.

fix: handle path standardization when bucket name not in path

---

ingestion_tools/scripts/importers/tomogram.py

Relates to
Handles the voxel spacing being a formatted string in the ingestion config

fix: handle formatted voxel spacing string in tomo metadata

---

ingestion_tools/scripts/importers/alignment.py
ingestion_tools/scripts/tests/s3_import/test_alignments.py
schema/core/v2.0.0/metadata.yaml

Relates to
>  this is necessary because tomograms of different voxel spacings should be able to have the same alignment.
so we have to specify the size independent of voxel spacing

fix: Updating alignment dimensions and offsets to Angstrom

---

ingestion_tools/dataset_configs/10000.yaml
ingestion_tools/dataset_configs/10001.yaml
ingestion_tools/dataset_configs/10002.yaml
ingestion_tools/dataset_configs/10004.yaml
ingestion_tools/dataset_configs/10007.yaml
ingestion_tools/dataset_configs/10008.yaml
ingestion_tools/dataset_configs/10009.yaml

Relates to
Normalize available files in existing configs to account for availability of new import tools.
- 10000: Add missing `tlt` files
- 10001: Add missing `tlt` files
- 10002: Add missing `tlt` and `rawtlt` files
- 10004: Add missing `rawtlt` files
- 10007: Add missing `tlt` files
- 10008: Add missing `rawtlt` files
- 10009: Add missing `rawtlt` files

chore: Fix/Complete available alignments for existing datasets

---

ingestion_tools/poetry.lock
ingestion_tools/pyproject.toml

Relates to N/A
Upgrade `cryoet-alignment` to 0.0.7, which contains a fix for reading newst.com files missing the AntialiasFilter option.

fix: Upgrade cryoet-alignment package to 0.0.7

---

apiv2/scripts/scrape.py

Copying data for dataset `10442` into the v2 db was causing one alignment to be generated per-tomogram. This change updates the copy script to only generate one alignment *per run*

fix: Only read one alignment per run from the V1 api into the V2 api

---

ingestion_tools/scripts/common/image.py

Relates to N/A
When Zarr-volumes are already ingested, the Importers attempt to get the shape from the `VolumeReader`. In the case of `OMEZarrReader`, even when `header_only=True`, it was attempted to use the unset `data` attribute. This PR adds private attribute `_shape` to the reader that stores the array shape without loading the data.

fix: Retrieve Zarr shape without having to load data

---

apiv2/db_import/importers/tomogram.py
ingestion_tools/scripts/importers/db/tomogram.py
ingestion_tools/scripts/tests/db_import/test_db_tomo_import.py

Sets the neuroglancer config to `None` for cases where there is no neuroglancer_config path specified in the tomogram metadata.

chore: Handle no neuroglancer config file

---

apiv2/db_import/importers/tomogram.py
apiv2/db_import/tests/populate_db.py
ingestion_tools/scripts/importers/db/tomogram.py
ingestion_tools/scripts/importers/tomogram.py
ingestion_tools/scripts/tests/db_import/populate_db.py

Relates to N/A
Tomograms are considered unique based on these fields during S3 ingestion: 
```
[
container_key,
str(voxel_spacing),
metadata.get("alignment_metadata_path", kwargs.get("alignment_metadata_path", "")),
metadata.get("reconstruction_method", ""),
metadata.get("processing", ""),
str(metadata.get("deposition_id", int(parents["deposition"].name))),
]
``` 
This PR adds `processing_software` to the hash function to be able to distinguish tomograms denoised using different tools. It also expands the ID fields for the `TomogramDBImporter`.

feat: Expand the Tomgram importer hash function to include processing software

---

ingestion_tools/scripts/common/config.py

Relates to N/A
In some cases `config.resolve_output_path` is used to resolve glob patterns, e.g:
- https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/9cf033ab930a7a11e971eac65efcbf6644a0b935/ingestion_tools/scripts/importers/tomogram.py#L23
- https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/9cf033ab930a7a11e971eac65efcbf6644a0b935/ingestion_tools/scripts/importers/alignment.py#L26
- https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/9cf033ab930a7a11e971eac65efcbf6644a0b935/ingestion_tools/scripts/importers/annotation.py#L28
These patterns should never be passed to` fs.makedirs()`. This is inconsequential on S3 (because this method is not implemented there), but creates spurious directories when used in `standardize_dirs.py convert ... …

fix: Prevent creating glob patterns as directories.

---

.github/workflows/push-ingestor-build.yaml
Makefile

This updates our `push-local-ingestor-build` make target to build both an apiv2 image (for db ingestion) and an ingestion_tools image (for s3 ingestion and apiv1 db ingestion) and also updates the GitHub action that pushes our ingestion_tools docker image to build an apiv2 image as well.
It's important to note that we've taken on this extra step because we run db ingestion in an x86-only environment in AWS batch, while our apiv2 service runs on ARM. We're using python and libraries that generally aren't tied to CPU architecture, so I don't expect any major differences in behavior between the different images

chore: Build an x86 version of the apiv2 image to execute in aws batch.

---

apiv2/poetry.lock

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1259
Upgrades fastapi from 0.115.0 -> 0.115.4 (the latest version)  as starlette is a requirement of it. 
Fastapi upgrades its starlette dependency in 0.115.2 : [Changelog](https://github.com/fastapi/fastapi/releases/tag/0.115.2)

chore: Bumping fastapi version to 0.115.0 -> 0.115.4

---

.github/workflows/push-ingestor-build.yaml

Secrets can't be specified as inputs to matrix builds, so we need to send the name of the secret KEY to the build job. Matrix values are also nested under a top level `matrix` object, so I updated the docker-build job accordingly. I tested this on a dev branch here:
https://github.com/chanzuckerberg/cryoet-data-portal-backend/actions/runs/11746537051/job/32726517971
Reference: https://sbulav.github.io/terraform/github-actions-matrix-secrets/

fix: matrix build variables behave oddly

---

ingestion_tools/dataset_configs/10311_draft.yaml
ingestion_tools/dataset_configs/template.yaml
ingestion_tools/scripts/common/finders.py

Relates to
Updates the [dep 10311 config file](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/2868b8bb99a9a942ef2be1e2f059b368d7bb0c1f/ingestion_tools/dataset_configs/deposition_10311_draft.yaml) for globs
The config was tested for `10015/pda2022-01-23-103/` in the test bucket.

feat: Creating standardized tomo config

---

apiv2/db_import/importer.py
ingestion_tools/docs/enqueue_runs.md
ingestion_tools/infra/db_import-v0.0.2.wdl
ingestion_tools/scripts/enqueue_runs.py

This adds a new WDL file that supports ingesting data into the v1 and v2 db's with the same `enqueue_runs.py` command. The docker image necessary to do this has already been added to our CI workflows.
NOTE: the WDL files have already been uploaded to s3, so this is ready to go.

fix: Support running v2 db import via batch job.

---

apiv2/db_import/importers/alignment.py

Relates to
https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/369
Removes `tiltseries_id` verification from the alignment importer

fix: remove tiltseries_id check from alignment importer

---

apiv2/db_import/common/config.py
apiv2/db_import/importers/alignment.py
apiv2/db_import/importers/annotation.py
apiv2/db_import/importers/tomogram.py

Relates to
Optimization for the look up of tiltseries and alignments. Adding an additional filter on the run id helps reduce the search space. 
This is especially useful as the look up criterion is text based comparison.

chore: Optimizing fetching alignments and tiltseries by paths

---

ingestion_tools/scripts/db_import.py

When running `enqueue_runs.py` with `--import-alignments` flag it will fail for v1 since that flag doesn't exist. This adds this flag to the function definition as a workaround to make sure the job does not fail when importing with the alignments flag.

fix: db_import updates for alignments

---

ingestion_tools/scripts/importers/alignment.py
ingestion_tools/scripts/tests/s3_import/test_alignments.py
ingestion_tools/scripts/tests/s3_import/test_annotations.py

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1384
Updates the alignment voxel spacing source to be the same as output tomogram's voxel spacing source.

fix: Update alignment volume_dim voxel source

---

ingestion_tools/scripts/db_import.py
ingestion_tools/scripts/importers/visualization_precompute.py

zfpy is a sub-sub-sub-dependency of our ingestion scripts, and it does not work properly with Python 3.12 on ARM macs. This workaround only imports the module when it's actually required and allows us to keep running enqueue scripts from our laptops.
(more traceback and info will be added to this ticket later)

chore: Workaround for py3.12 on osx issue.

---

apiv2/scripts/scrape.py

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1389 
Once, the data is in the v2 database's table, it is never required for it to be updated by the data in v1 api. It is better for it to be updated by the db-import script. 
This changes the scrape script to not overwrite the data, if it already exists in the database.

fix: scrape script overwriting existing v2 data

---

apiv2/db_import/importers/tomogram.py
apiv2/db_import/tests/test_db_tomo_import.py
test_infra/test_files/30001/RUN1/Reconstructions/VoxelSpacing12.300/Tomograms/100/tomogram_metadata.json

We were erroneously replacing spaces with underscores for the reconstruction software field when importing metadata to the db. This fixes the issue and updates the tests to reflect the change.
Relates to

fix: Don't replace spaces with underscores for reconstruction software.

---

apiv2/conftest.py
apiv2/graphql_api/types/alignment.py
apiv2/graphql_api/types/annotation.py
apiv2/graphql_api/types/annotation_author.py
apiv2/graphql_api/types/annotation_file.py
apiv2/graphql_api/types/annotation_method_link.py
apiv2/graphql_api/types/annotation_shape.py
apiv2/graphql_api/types/dataset.py
apiv2/graphql_api/types/dataset_author.py
apiv2/graphql_api/types/dataset_funding.py
apiv2/graphql_api/types/deposition.py
apiv2/graphql_api/types/deposition_author.py
apiv2/graphql_api/types/deposition_type.py
apiv2/graphql_api/types/frame.py
apiv2/graphql_api/types/frame_acquisition_file.py
apiv2/graphql_api/types/gain_file.py
apiv2/graphql_api/types/per_section_alignment_parameters.py
apiv2/graphql_api/types/run.py
apiv2/graphql_api/types/tiltseries.py
apiv2/graphql_api/types/tomogram.py
apiv2/graphql_api/types/tomogram_author.py
apiv2/graphql_api/types/tomogram_voxel_spacing.py
apiv2/platformics/graphql_api/core/query_builder.py
apiv2/platformics/graphql_api/core/strawberry_helpers.py
apiv2/template_overrides/graphql_api/types/class_name.py.j2
apiv2/tests/helpers.py
apiv2/tests/test_aggregate_filters.py
apiv2/tests/test_gql_meta_support.py

Adds support for including `__typename` and other graphql-reserved keywords in GraphQL queries. Our API was making naive/incorrect assumptions about query field ordering and also assuming that only application-specific fields would be present in queries. This updates our application code to filter out any GraphQL reserved fields (such as `__typename`) before interpreting queries. 
Some GraphQL clients (like Apollo) include `__typename` fields in every level of a GraphQL query to help with type interpretation. We've had to disable this functionality in our frontend to work around the issue in our API. We should be able to turn it back on now.

fix: support __typename fields in gql queries

---

ingestion_tools/scripts/enqueue_runs.py
ingestion_tools/scripts/tests/db_import/test_db_tomo_import.py

Relates to ~
> Ais deposition ingestion and one issue I'm running into is that I can't enqueue certain jobs because the [name truncation here](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/32bde071d117e3ba27abeb7d28d31c181d158e76/ingestion_tools/scripts/enqueue_runs.py#L449-L450) leads to jobs having the same name when I want to re-run them, i.e. I get a botocore.errorfactory.ExecutionAlreadyExists exception. Also, this exception is occuring silently because enqueue_runs doesn't check the result of the concurrent futures.
Addresses the issue mentioned above.

chore: Updating long execution name generation

---

ingestion_tools/scripts/importers/annotation.py

Relates to N/A
When ingesting SegmentationMasks that require rescaling, the volume dimensions are retrieved from the alignment metadata. This PR fixes where the metadata are read from (i.e. the `AlignmentImporter.metadata` rather than the output of `AlignmentImporter.get_extra_metadata`). 
This is a fix enabling ingestion of the Ais deposition from #363

fix: Retrieve volume_dimension alignment metadata correctly when rescaling segmentation masks during ingestion.

---

ingestion_tools/scripts/importers/dataset_key_photo.py

Relates to N/A
When importing an annotation deposition using a `destination_glob` for datasets, the import of `dataset_keyphotos` should also be disallowed. This is achieved here by overriding the `DatasetKeyPhotoImporter`'s `is_import_allowed` method with the result of the parent's method. 
Needed to avoid errors when running import for the Ais deposition (#363)

fix: Do not attempt to import dataset keyphoto when dataset is not being imported

---

ingestion_tools/scripts/common/image.py
ingestion_tools/scripts/importers/annotation.py

Relates to N/A
When checking if a SegmentationMask annotation is valid the threshold (if it exists) needs to be passed to the MaskConverter. When a threshold is applied, the mask is checked for any value > threshold instead of simply checking for the presence of the mask label. This PR fixes that by adding the threshold as an optional argument to the validity check.
Required for correctly ingesting the Ais deposition. (#363)

fix: Include threshold when checking mask annotation validity

---

apiv2/platformics/codegen/templates/test_infra/factories/class_name.py.j2
apiv2/test_infra/factories/alignment.py
apiv2/test_infra/factories/annotation.py
apiv2/test_infra/factories/annotation_author.py
apiv2/test_infra/factories/annotation_file.py
apiv2/test_infra/factories/annotation_method_link.py
apiv2/test_infra/factories/annotation_shape.py
apiv2/test_infra/factories/dataset.py
apiv2/test_infra/factories/dataset_author.py
apiv2/test_infra/factories/dataset_funding.py
apiv2/test_infra/factories/deposition.py
apiv2/test_infra/factories/deposition_author.py
apiv2/test_infra/factories/deposition_type.py
apiv2/test_infra/factories/frame.py
apiv2/test_infra/factories/frame_acquisition_file.py
apiv2/test_infra/factories/gain_file.py
apiv2/test_infra/factories/per_section_alignment_parameters.py
apiv2/test_infra/factories/run.py
apiv2/test_infra/factories/tiltseries.py
apiv2/test_infra/factories/tomogram.py
apiv2/test_infra/factories/tomogram_author.py
apiv2/test_infra/factories/tomogram_voxel_spacing.py

We've been seeing intermittent apiv2 test failures in our pull requests.
We use a test fixture library called `factory_boy` to generate semi-randomized database rows in our tests. This tool works great, when it's configured properly! However we were generating object ID's like so:
```
id = fuzzy.FuzzyInteger(1, 1000)
```
This tells the test fixture to use a random number between 1 and 1000 for each object ID. Our tests were failing sporadically because sometimes when we told the fixture to make a batch of N rows, some of those rows would get generated with the same identifier, and get collapsed into a single row!
This PR updates the fixture configuration to use factory_boy's [Sequences](https://factoryboy.readthedocs.io/en/stable/#sequences) functionality to generate sequential ID's …

fix: Fix for spurious test failures.

---

apiv2/graphql_api/helpers/alignment.py
apiv2/graphql_api/helpers/annotation.py
apiv2/graphql_api/helpers/dataset.py
apiv2/graphql_api/helpers/deposition.py
apiv2/graphql_api/helpers/tomogram.py
apiv2/platformics/codegen/templates/graphql_api/helpers/class_name.py.j2
apiv2/tests/test_aggregates.py

We had a bad assumption in our `group_by` query handling where we were expecting each relationship (like the relationship between datasets and dataset authors) to have the same name as the related class (in our example, we expect the field on datasets to be `dataset.dataset_authors`), which is definitely not the case! We can support *multiple* relationships between two types, so long as each relationship has its own name.
This fix updates codegen to use the name of the *relationship name* to unpack our SQL data into GraphQL response types instead of the *related table name*, and adds a test for this case.

fix: fix response handling for grouping by related fields 

---

ingestion_tools/scripts/enqueue_runs.py

Relates to N/A
The fixed determination of execution name length still had a minor issue. We need to consider the `"-run"` part that is not contained in the prefix, and thus use 76 as maximum run name length instead of 80.

fix: Execution name length determination for enqueue

---

ingestion_tools/dataset_configs/10003.yaml

Relates to N/A
Dataset 10003 was missing tilt series, rawtlts and collection metadata. They are added by this PR.

fix: Add tilt series, rawtlt and mdoc to 10003

---

ingestion_tools/poetry.lock
ingestion_tools/pyproject.toml

The main goal is to update the [cryoet-data-portal-neuroglancer](https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer) version to 1.2.1. Overall this should mean that the following are available in a neuroglancer link from the portal after ingestion:
1. Hide the opaque, single-color background of the orthoplanes in the 3D view of the tomogram
2. opacity slider - additive blending
3. Hide shader code from users
4. Disable "pick" for segmentation layer
5. Color legend relating an annotation displayed in 2D or 3D to its respective tab or sidebar entry in Neuroglancer (this is setup to be ready if the change is made to main neuroglancer - won't immediately appear until then)
See the [changelog](https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/blob/main/CHANGELOG.m …

chore: update cryoet data portal neuroglancer version from 1.0.1 to 1.2.3

---

ingestion_tools/scripts/importers/visualization_precompute.py

Relates to n/a
The cryoet-data-portal-neuroglancer function `encode_segmentation` being called here to convert a segmentation to the neuroglancer precomputed format expects the resolution to be in nanometers, but the provided voxel resolution seems to be in angstrom.
This won't have any noticeable effect on the production version of the portal, because the JSON state generator called in `_to_segmentation_mask_layer` is overriding this value with the correct resolution via a co-ordinate transform.
Providing the correct resolution to the conversion function would be nice to change just for consistency.

fix: convert angstrom resolution to nm resolution in precompute seg

---

schema/ingestion_config/v1.0.0/ingestion_config_models_extended.py

When making network requests to api.crossref.org to validation publication DOIs, we currently try to make a `HEAD` request to a URL along the lines of `https://api.crossref.org/works/{doi}/agency`. However, an 405 error (Method Not Allowed) status now appears, likely because there should only be `GET` requests getting sent to this endpoint. As a fix, we just make a `HEAD` request to `https://api.crossref.org/works/{doi}`, which properly validates the DOI and does not give this 405 error. 
For reference: 
https://api.crossref.org/swagger-ui/index.html#:~:text=Headers%20only%3A%20you,org/members/98%22

fix: doi publication validation bug

---

ingestion_tools/dataset_configs/10301.yaml
ingestion_tools/dataset_configs/10441.yaml
schema/Makefile
schema/core/v2.0.0/codegen/metadata_materialized.yaml
schema/core/v2.0.0/codegen/metadata_models.py
schema/core/v2.0.0/common.yaml
schema/core/v2.0.0/metadata.yaml
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json
schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml
schema/ingestion_config/v1.0.0/ingestion_config_models.yaml
schema/metadata_files/v2.0.0/codegen/metadata_files.py
schema/metadata_files/v2.0.0/codegen/metadata_files.schema.json
schema/metadata_files/v2.0.0/codegen/metadata_files_materialized.yaml
schema/metadata_files/v2.0.0/metadata_files.yaml

Relates to Global Image Labels https://github.com/chanzuckerberg/cryoet-data-portal/issues/1823
In order to support global image labels, the respective fields and classes need to be added to the ingest config container and the metadata file schema. 
**Changes to common.yaml (fields common across schemas)**
Add common slots:
-  `identified_object_description`
-  `identified_object_id`
-  `identified_object_name`
-  `identified_object_state`
-  `identified_object_filter_value`
**Changes to metadata.yaml (classes common across schemas)**
Add Classes:
- `IdentifiedObject` (aggregation of id, name, state, description)
- `IdentifiedObjectList` (metadata of the input file, i.e. filter value)
**Changes to ingestion_config_models.yaml (ingest config schema)**
Add Class:
- `IdentifiedObjectEntity` …

feat: Addition of global image labels to ingest config schema and metadata file schema. 
