chanzuckerberg/cryoet-data-portal-backend

ingestion_tools/dataset_configs/10000.yaml, ingestion_tools/dataset_configs/10001.yaml, ingestion_tools/dataset_configs/10002.yaml, ingestion_tools/dataset_configs/10003.yaml, ingestion_tools/dataset_configs/10004.yaml, ingestion_tools/dataset_configs/10005.yaml, ingestion_tools/dataset_configs/10006.yaml, ingestion_tools/dataset_configs/10007.yaml, ingestion_tools/dataset_configs/10008.yaml, ingestion_tools/dataset_configs/10009.yaml, ingestion_tools/dataset_configs/10010.yaml
Reimports required:
- 10000: Dataset metadata, Annotation metadata
- 10001: Annotation metadata
- 10002: Annotation metadata
- 10003: Annotation metadata
- 10004: Annotation metadata
- 10005: Annotation metadata
- 10006: Annotation metadata
- 10007: Annotation metadata
- 10008: Annotation metadata
- 10009: Dataset metadata, Annotation metadata
- 10010: Annotation metadata
=> Add method type to 10000 - 10010 and fix various metadata errors found along the way

.github/workflows/staging-deploy.yaml
Rerun staging workflow when updating workflow yaml.
=> Updating staging deploy gh worflow

api_server/metadata/databases/cryoetdataportal/tables/public_annotation_files.yaml
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/383
Making is_visualization_default field public for anonymous user
=> Making is_visualization_default field public for anonymous user

ingestion_tools/.dockerignore, ingestion_tools/docs/enqueue_runs.md, ingestion_tools/infra/standardize_dirs.wdl-v0.0.1.wdl, ingestion_tools/scripts/enqueue_runs.py
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/485
- Adds help to enqueue job
- Updates path in the wdl to reflect new path
- Adds doc for enqueuing the job
=> fix: Updating batch job

.github/workflows/py-formatting.yml, schema/pyproject.toml, schema/v1.1.0/Makefile, schema/v1.1.0/schema.py
- Updates pre-commit to only run on files that have been updated.
=> chore: Updating pre-commit config to run on modified files

ingestion_tools/scripts/common/config.py, ingestion_tools/scripts/common/normalize_fields.py
Some of our input values were *string* "True" and "False" values, so this updates our normalizer to handle those. Plus some tweaks to handle empty config vars better.
=> Updates to handle stringified booleans

ingestion_tools/dataset_configs/10301.yaml, ingestion_tools/scripts/common/config.py
1. updating tilt_range keys to match the tsv file key
2. Creating paths using `os.path.join` to handle `/` more gracefully.
=> chore: minor fixes

ingestion_tools/dataset_configs/10301.yaml, ingestion_tools/dataset_configs/template.yaml
Adding `annotation.method_type` to dataset config 10301.yaml
=> chore: Adding method_type to config template

ingestion_tools/dataset_configs/10301.yaml, ingestion_tools/dataset_configs/10302.yaml, ingestion_tools/scripts/tomoman_to_tsv.py
- First stab at ingestion config for 10302
- changes to tomoman_to_tsv.py concerning this dataset: gainref location, check for presence of defect file entry
- fix for 10301: location of some rawtlt files.
=> Ingestion config for 10302 and required fixes

ingestion_tools/dataset_configs/10008.yaml
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/396
=> chore: Making annotation object name consistent

ingestion_tools/scripts/enqueue_runs.py
Adds support to skip runs until a specific run name.
=> feat: Updating enqueue to support skip-until

.github/workflows/push-ingestor-build.yaml, Makefile
Fixes the permission for pushing the image to ECR for the github workflow.
=> Fix permissions for docker token in github workflow

.github/workflows/push-ingestor-build.yaml, ingestion_tools/scripts/enqueue_runs.py
the ECR-push github action was broken - this fixes it. I tested it on a branch a few minutes ago.
=> Fix docker push

ingestion_tools/dataset_configs/deposition_10302.yaml, ingestion_tools/docs/standardize_dirs.md, ingestion_tools/scripts/enqueue_runs.py, ingestion_tools/scripts/standardize_dirs.py
- Ingestion config for braxton annotations
- Fixes to standardize_dirs docs
- Some extra useful debugging in the standardize_dirs script
- Fixes for broken enqueue script
=> Ingestion config for braxton annotations + some fixes

ingestion_tools/dataset_configs/10002.yaml, ingestion_tools/dataset_configs/10010.yaml
Removing tissue data per this issue -- https://github.com/chanzuckerberg/cryoet-data-portal/issues/694
=> Update tissue metadata for cultured cells

ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10304.yaml
Populated metadata and source paths for membrain runs and membrane segmentations from Min Xu's group.
=> Ingestion configs for membrain and 10304

ingestion_tools/scripts/common/image.py
- Fixes the validation check for SemanticSegmentationMask
- Updates `TomoConverter.tomo_reader` -> `TomoConverter.volume_reader` as it is also used by non-tomogram assets
- Minor fix related to fetching `VolumeInfo`
=> Volume handlers minor fixes

ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10303_gas_vesicles.yaml, ingestion_tools/dataset_configs/deposition_10304.yaml
Ingest membrain predictions for 10014-10020 as gas vesicle instead of as membrane.
=> Fix annotated object for membrain outputs in 10014-10020

ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10303_gas_vesicles.yaml
The regex patterns match against the whole path, not just the dataset names. Adjusted patterns accordingly.
=> Fix regex for deposition 10303

ingestion_tools/dataset_configs/gjensen/10105.yaml, ingestion_tools/dataset_configs/gjensen/10106.yaml, ingestion_tools/dataset_configs/gjensen/10107.yaml, ingestion_tools/dataset_configs/gjensen/10108.yaml, ingestion_tools/dataset_configs/gjensen/10169.yaml, ingestion_tools/dataset_configs/gjensen/10170.yaml, ingestion_tools/dataset_configs/gjensen/10171.yaml, ingestion_tools/dataset_configs/gjensen/10172.yaml, ingestion_tools/dataset_configs/gjensen/10173.yaml, ingestion_tools/dataset_configs/gjensen/10174.yaml, ingestion_tools/dataset_configs/gjensen/10175.yaml, ingestion_tools/dataset_configs/gjensen/10176.yaml, ingestion_tools/dataset_configs/gjensen/10177.yaml, ingestion_tools/dataset_configs/gjensen/10178.yaml, ingestion_tools/dataset_configs/gjensen/10179.yaml, ingestion_tools/dataset_configs/gjensen/10180.yaml, ingestion_tools/dataset_configs/gjensen/10181.yaml, ingestion_tools/dataset_configs/gjensen/10182.yaml, ingestion_tools/dataset_configs/gjensen/10183.yaml, ingestion_tools/dataset_configs/gjensen/10184.yaml, ingestion_tools/dataset_configs/gjensen/10185.yaml, ingestion_tools/dataset_configs/gjensen/10186.yaml, ingestion_tools/dataset_configs/gjensen/10187.yaml, ingestion_tools/dataset_configs/gjensen/10188.yaml
These field names were inaccurate and can't be read by the db import script
=> Fix cell type field names.

ingestion_tools/scripts/importers/visualization_precompute.py
Fixes path for instance segmentation's visualization path.
=> Fix instance seg viz path

ingestion_tools/scripts/importers/visualization_config.py
Removing exclusion of colors used by instance segmentations, to help the colors be more consistent and visually distinct across different annotations.
=> Improving color choices for neuroglancer

ingestion_tools/docs/enqueue_runs.md, ingestion_tools/infra/sync-v0.0.1.wdl, ingestion_tools/scripts/enqueue_runs.py
Add `aws s3 sync` support (on a per-dataset basis) to the `enqueue_runs.py` script.
Note that this command supports the same `--include/--exclude` interface that `aws s3 sync` does, so order of those arguments matters!
=> feat: Support syncing files from staging to prod.

ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10303_gas_vesicles.yaml
Adds the [preprint](https://doi.org/10.1101/2024.01.05.574336) to the annotation metadata of `deposition_10303` and `deposition_10303_gas_vesicles`.
=> Add membrain pre-print reference

ingestion_tools/docs/enqueue_runs.md, ingestion_tools/scripts/enqueue_runs.py
- Adds ability to exclude datasets when running filter datasets for db import or s3 sync
=> Adding exclude to enqueue db import and s3 sync

ingestion_tools/dataset_configs/10301.yaml
Relates to
N/A
Provide the correct GO-ID for ribosomes in 10301.
=> fix incorrect object_id

.pre-commit-config.yaml, ingestion_tools/dataset_configs/.gitignore, ingestion_tools/dataset_configs/template.yaml, ingestion_tools/scripts/dataset_config_merge.py
Update dataset configuration template file as per https://github.com/chanzuckerberg/cryoet-data-portal/issues/825. 
Reflects current dataset config files' structure. A precursor step to creating validation for ingesting dataset config files and updating the database's schema / linkml files.
=> Update dataset configuration template file

ingestion_tools/dataset_configs/10301.yaml
Change the extension for gain file finder pattern to actually find the gain files.
=> Correct gain file extension for 10301

ingestion_tools/scripts/common/config.py, ingestion_tools/scripts/common/finders.py, ingestion_tools/scripts/common/fs.py, ingestion_tools/scripts/importers/gain.py, ingestion_tools/scripts/importers/run.py, ingestion_tools/scripts/tests/fixtures/dataset1.yaml, ingestion_tools/scripts/tests/s3_import/test_gains.py
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/858
When gain file has a non `.dm4` extension, we copy the file over with the extension in the source file, and we continue to maintain the behaviour of retaining the `.mrc` extension for the `.dm4` files.
=> Supporting different extensions for gains

ingestion_tools/dataset_configs/10426.yaml, ingestion_tools/dataset_configs/10427.yaml, ingestion_tools/dataset_configs/10428.yaml, ingestion_tools/dataset_configs/10429.yaml, ingestion_tools/dataset_configs/10430.yaml, ingestion_tools/dataset_configs/10431.yaml, ingestion_tools/dataset_configs/10432.yaml, ingestion_tools/dataset_configs/10433.yaml, ingestion_tools/dataset_configs/10434.yaml, ingestion_tools/dataset_configs/10435.yaml
Changing the values to have a valid cell ontology term in cell_type and a cell line ontology term in cell_strain.
=> Change cell_strain and cell_type of 10426-10435 to conform to new validation rules

ingestion_tools/scripts/tomoman_to_tsv.py
Update the run map generation to refactor the gain reference. The dataset has the issue, that some of the gain references are incorrect as the files specified don't exist. Address this by mapping the gain references that have invalid paths, but same name of existing gain references, to the existing gain references.
=> Updates to tomolist script

ingestion_tools/dataset_configs/template.yaml
Add parent_filters option, as permitted by the ingestion process (schema / validation also reflects this)
=> fix template.yaml annotation sources

ingestion_tools/dataset_configs/10000.yaml, ingestion_tools/dataset_configs/10001.yaml
Updates the match_regex field for tiltseries to match the glob.
=> fix: Updating config match regex 

ingestion_tools/dataset_configs/10003.yaml, ingestion_tools/dataset_configs/10006.yaml, ingestion_tools/dataset_configs/10426.yaml, ingestion_tools/dataset_configs/10427.yaml, ingestion_tools/dataset_configs/10428.yaml, ingestion_tools/dataset_configs/10429.yaml, ingestion_tools/dataset_configs/10430.yaml, ingestion_tools/dataset_configs/10431.yaml, ingestion_tools/dataset_configs/10432.yaml, ingestion_tools/dataset_configs/10433.yaml, ingestion_tools/dataset_configs/10434.yaml, ingestion_tools/dataset_configs/10435.yaml, ingestion_tools/scripts/common/image.py, ingestion_tools/scripts/importers/base_importer.py
- Minor refactor to make a method name more generalized, as the method is used for both tiltseries volumes and tomogram volumes. 
- Updating the sources for the unavailable tiltseries to return empty list instead of causing error during ingestion
=> chore: minor refactors

api_server/metadata/databases/cryoetdataportal/tables/public_annotations.yaml, api_server/migrations/cryoetdataportal/1722371992711_alter_table_public_annotations_add_column_method_links/down.sql, api_server/migrations/cryoetdataportal/1722371992711_alter_table_public_annotations_add_column_method_links/up.sql, api_server/migrations/cryoetdataportal/1722372067853_create_index_annotation_method/down.sql, api_server/migrations/cryoetdataportal/1722372067853_create_index_annotation_method/up.sql, ingestion_tools/scripts/common/db_models.py, ingestion_tools/scripts/importers/db/annotation.py, ingestion_tools/scripts/tests/db_import/test_db_annotation_import.py, test_infra/sql/schema.sql, test_infra/test_files/30001/RUN1/Tomograms/VoxelSpacing12.300/Annotations/100-foo-1.0.json
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/930
- Adds index on `annotation_method` field to optimize for the group by queries on it for the deposition page
- Adds a new field for annotation method link, that would be a stored as a json to preserve the link type, link custom name and link.
=> Adding deposition support for annotations

ingestion_tools/dataset_configs/deposition_10301.yaml, ingestion_tools/dataset_configs/deposition_10302.yaml, ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10303_gas_vesicles.yaml, ingestion_tools/dataset_configs/deposition_10304.yaml, ingestion_tools/dataset_configs/deposition_10305.yaml, ingestion_tools/dataset_configs/deposition_10307.yaml
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/876
Deposition titles and descriptions for annotations depositions.
=> Titles and descriptions for annotation depositions.

ingestion_tools/scripts/importers/annotation.py
- Adds comments and decorators to explicitly call out methods that need to be overridden for annotations
=> Refactoring annotation importer

.github/workflows/argus-stack-prod-upsert.yaml, .github/workflows/argus-stack-rdev-create.yaml, .github/workflows/argus-stack-rdev-delete.yaml, .github/workflows/argus-stack-staging-upsert.yaml, .github/workflows/conventional-commits.yml, .github/workflows/docker-build-rdev.yaml, .github/workflows/docker-build-staging-prod.yaml, .github/workflows/release-please.yaml, .github/workflows/workflow-argus-docker-build.yaml, .infra/common.yaml, .infra/prod/Chart.yaml, .infra/prod/values.yaml, .infra/rdev/Chart.yaml, .infra/rdev/values.yaml, .infra/staging/Chart.yaml, .infra/staging/values.yaml, apiv2/etc/gen_keys.sh
=> initial setup

schema/Makefile, schema/api/v1.0.0/api_models.yaml, schema/api/v1.0.0/codegen/ER_DIAGRAM.md, schema/api/v1.0.0/codegen/api_models_materialized.yaml, schema/api/v2.0.0/api_models.yaml, schema/api/v2.0.0/codegen/ER_DIAGRAM.md, schema/api/v2.0.0/codegen/api_models_materialized.yaml
Relates to
Adds ER diagram generation to the make command, such that the er diagram will be updated to reflect the changes to api schema. 
[Sample ER diagram](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/363c64ca6aaefd3a01355b084a3b811d36d072c4/schema/api/v1.0.0/codegen/ER_DIAGRAM.md).
The dataset is set as root of the diagram, to help maintain consistency between different versions of the diagram.
=> Adding ER Diagrams to api schema

schema/Makefile, schema/ingestion_config/v1.0.0/ingestion_config_models_extended.py, schema/ingestion_config/v1.0.0/ingestion_config_validate.py
ingestion validation fixes & improvements
- better logging
- bugfix extended validation and add some missing checks
- add validation for new sources feature introduced in #211
=> ingestion config fixes

ingestion_tools/dataset_configs/10440_draft.yaml, ingestion_tools/dataset_configs/10441_draft.yaml
Reserving dataset IDs (10440, 10441) and deposition ID (10310) for ML challenge datasets.
=> Reserve dataset IDs for ML challenge data.

schema/api/v1.0.0/codegen/ER_DIAGRAM.md, schema/api/v1.0.0/codegen/api_models_materialized.yaml, schema/core/v1.1.0/codegen/metadata_materialized.yaml, schema/core/v1.1.0/codegen/metadata_models.py, schema/core/v1.1.0/common.yaml, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml
tomogrom_reconstruction_method_enum -> tomogram_reconstruction_method_enum
=> fix tomogrom -> tomogram typo

apiv2/scrape.py
=> feat: Update scrape tool to handle alignments and depositions.

.github/workflows/workflow-argus-docker-build.yaml, apiv2/README.md
=> fix: use supported github workflows.

.github/workflows/argus-stack-staging-upsert.yaml, .github/workflows/docker-build-staging-prod.yaml, apiv2/README.md
=> chore: update actions to use per-component branch names

.github/workflows/docker-build-staging-prod.yaml, apiv2/README.md
=> fix: more ci fixes.

.github/workflows/docker-build-staging-prod.yaml
=> chore: Fix filters for docker build for staging/prod

apiv2/schema/schema.yaml, ingestion_tools/dataset_configs/template.yaml, schema/api/v1.0.0/api_models.yaml, schema/api/v1.0.0/codegen/ER_DIAGRAM.md, schema/api/v1.0.0/codegen/api_models_materialized.yaml, schema/api/v2.0.0/api_models.yaml, schema/api/v2.0.0/codegen/ER_DIAGRAM.md, schema/api/v2.0.0/codegen/api_models_materialized.yaml, schema/core/v1.1.0/codegen/metadata_materialized.yaml, schema/core/v1.1.0/codegen/metadata_models.py, schema/core/v1.1.0/common.yaml, schema/core/v1.1.0/metadata.yaml, schema/core/v2.0.0/codegen/metadata_materialized.yaml, schema/core/v2.0.0/common.yaml, schema/core/v2.0.0/metadata.yaml, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml
- Updates the method_links field name to `custom_name` to prevent confusions
- Updates the common v2 schema to match field names with v2 api schema
- Adds the method_links to the api_schema
=> chore: Updating configs and validation

ingestion_tools/docs/enqueue_runs.md, ingestion_tools/scripts/enqueue_runs.py, ingestion_tools/scripts/importers/db/deposition.py
Relates to 
Adds sync capability for deposition folders to the enqueue script. 
Example:
```
python enqueue_runs.py sync --include-deposition 10301 --dryrun --no-sync-dataset
```
The command above should do a dryrun to sync only the deposition metadata for deposition_id = 10301
=> Adding sync to deposition

.infra/common.yaml, .infra/prod/values.yaml, .infra/rdev/values.yaml, .infra/staging/values.yaml, apiv2/README.md
This updates the base image url for our deployments
=> chore: Change ecr urls to reflect multi-repo support.

apiv2/scrape.py
=> chore: Add convenience to switch to staging for scraping data.

apiv2/README.md, apiv2/scrape.py
=> feat: add docs for release

ingestion_tools/dataset_configs/10000.yaml, ingestion_tools/dataset_configs/10003.yaml, ingestion_tools/dataset_configs/10004.yaml, ingestion_tools/dataset_configs/10005.yaml, ingestion_tools/dataset_configs/10006.yaml, ingestion_tools/dataset_configs/10007.yaml, ingestion_tools/dataset_configs/10008.yaml, ingestion_tools/dataset_configs/10009.yaml, ingestion_tools/dataset_configs/10010.yaml, ingestion_tools/dataset_configs/10301.yaml, ingestion_tools/dataset_configs/10436.yaml, ingestion_tools/dataset_configs/10439.yaml
Updates deposition types to include annotation for dataset depositions that include annotation in them.
=> chore: Updating deposition types

apiv2/scripts/scrape.py, apiv2/scripts/validate.py
The frontend team noticed some data missing from the v2 api. I wrote a script to check for empty db columns, and updated the sync script to make sure we're copying over the missing data.
=> fix: Update sync script to sync missing fields.

apiv2/db_import/importers/tiltseries.py, apiv2/scripts/scrape.py
This PR updates the script that copies data over from the v1 api to support importing deposition_types and annotation.method_links
=> feat: Support scraping deposition_types and annotation_method_links

ingestion_tools/dataset_configs/deposition_10301.yaml, ingestion_tools/dataset_configs/deposition_10302.yaml, ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10304.yaml, ingestion_tools/dataset_configs/deposition_10305.yaml, ingestion_tools/dataset_configs/deposition_10308.yaml, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml, schema/ingestion_config/v1.0.0/ingestion_config_models.yaml
Relates to
- Adds a reference to the default alignment for depositions 10301 - 10308
- Updates the destination_glob for finding voxelspacing. `Tomograms`-> `Reconstructions`
- Updates the ingestion_config validation to make alignment metadata and sources optional
=> chore: Updating deposition configs for new folder structure

ingestion_tools/dataset_configs/deposition_10301.yaml, ingestion_tools/scripts/common/finders.py
Relates to
- Handles an edge case for defining the entity from metadata file where the default alignment has no valid files defined.
- Update the deposition 10301 to remove an invalid metadata field.
=> fix: Update metadata handling in finder

ingestion_tools/dataset_configs/10008.yaml
Relates to
Fixes the glob pattern to not be regex, as this is not parsed by s3 as a regex would be.
=> fix: list glob pattern to not be regex

ingestion_tools/scripts/common/alignment_converter.py
Relates to
Return empty list if no alignment file is available for AreTomo.
=> fix: Handle no alignment in AreTomo Converter

ingestion_tools/poetry.lock, ingestion_tools/pyproject.toml
Relates to N/A
Use upgraded version of `cryoet-alignment` that introduces a fix for reading `tilt.com` files
=> fix: Upgrade cryoet-alignment package.

apiv2/scripts/scrape.py
Updates the scrape script that copies data from the v1 to v2 api's to support reading data from local dev.
=> chore: Update scrape script to support local dev.

apiv2/.devcontainer/devcontainer.json, apiv2/README.md, apiv2/platformics/graphql_api/core/query_builder.py, apiv2/tests/test_where_clauses.py
=> fix: fixes for filtering on related fields.

ingestion_tools/dataset_configs/10440.yaml
Relates to
Fixing dataset title.
=> fix: Challenge data config fixes

apiv2/db_import/importers/dataset.py, apiv2/db_import/tests/populate_db.py, apiv2/db_import/tests/test_db_dataset_import.py, ingestion_tools/scripts/importers/db/dataset.py, ingestion_tools/scripts/tests/db_import/populate_db.py, ingestion_tools/scripts/tests/db_import/test_db_dataset_import.py, test_infra/test_files/30001/dataset_metadata.json
We need to make sure both v1 and v2 db ingestion include `grant_id` as part of the primary key for a dataset funding row.
=> fix: Make sure we support multiple grants for a given funding agency.

ingestion_tools/scripts/importers/visualization_config.py, ingestion_tools/scripts/tests/fixtures/dataset2.yaml, ingestion_tools/scripts/tests/s3_import/test_alignments.py, ingestion_tools/scripts/tests/s3_import/test_visualization_config.py
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1059
- Fixes the rendering of oriented point in neuroglancer.
- Adds tests for viz config generation
=> fix: Oriented point rendering in Neuroglancer

ingestion_tools/dataset_configs/10000.yaml, ingestion_tools/dataset_configs/10003.yaml, ingestion_tools/dataset_configs/10004.yaml, ingestion_tools/dataset_configs/10005.yaml, ingestion_tools/dataset_configs/10006.yaml, ingestion_tools/dataset_configs/10007.yaml, ingestion_tools/dataset_configs/10008.yaml, ingestion_tools/dataset_configs/10009.yaml, ingestion_tools/dataset_configs/10010.yaml, ingestion_tools/dataset_configs/10301.yaml, ingestion_tools/dataset_configs/10436.yaml, ingestion_tools/dataset_configs/10439.yaml, ingestion_tools/dataset_configs/10440.yaml, ingestion_tools/dataset_configs/10441.yaml, ingestion_tools/dataset_configs/10442.yaml, ingestion_tools/dataset_configs/deposition_10301.yaml, ingestion_tools/dataset_configs/deposition_10302.yaml, ingestion_tools/dataset_configs/deposition_10303.yaml, ingestion_tools/dataset_configs/deposition_10304.yaml, ingestion_tools/dataset_configs/deposition_10305.yaml, ingestion_tools/dataset_configs/deposition_10308.yaml
Relates to N/A
Adds key photos to all dataset or deposition configs that describe a deposition that includes annotations.
=> feat: Add deposition key photos to all deposition configs that include annotations.

ingestion_tools/dataset_configs/10436.yaml
Relates to
Fixes the alignment and raw tlt sources for dataset 10436.
=> fix: Updating ingestion config

ingestion_tools/dataset_configs/10439.yaml, ingestion_tools/dataset_configs/10441.yaml
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1076
Method type `simulated` was introduced for simulated data, but never updated in the ingestion configs for simulated data. Fixed here.
=> fix: Use method type 'simulated' for 10439 and 10441

apiv2/db_import/importer.py, apiv2/db_import/importers/alignment.py, apiv2/db_import/importers/base.py, apiv2/db_import/tests/populate_db.py, apiv2/db_import/tests/test_db_alignment_import.py, test_infra/test_files/30001/RUN1/Alignments/100/alignment_metadata.json
Relates to [Add support for perSectionAlignmentParameters to the v2 db ingestion process](https://github.com/chanzuckerberg/cryoet-data-portal/issues/1332)
Added Per Section Alignment Parameters Importer + Tests
=> feat: Support for Per Section Alignment Parameters DB Import

ingestion_tools/dataset_configs/10436.yaml
Fixes the alignment config to fetch the correct files.
=> fix: Updating alignment config for ds 10436

ingestion_tools/dataset_configs/10444.yaml
Relates to N/A
Ingestion config for isolated lysosome dataset.
=> feat: First ingestion config for lysosome datasets from CZII

apiv2/graphql_api/types/alignment.py, apiv2/graphql_api/types/annotation.py, apiv2/graphql_api/types/annotation_author.py, apiv2/graphql_api/types/annotation_file.py, apiv2/graphql_api/types/annotation_method_link.py, apiv2/graphql_api/types/annotation_shape.py, apiv2/graphql_api/types/dataset.py, apiv2/graphql_api/types/dataset_author.py, apiv2/graphql_api/types/dataset_funding.py, apiv2/graphql_api/types/deposition.py, apiv2/graphql_api/types/deposition_author.py, apiv2/graphql_api/types/deposition_type.py, apiv2/graphql_api/types/frame.py, apiv2/graphql_api/types/frame_acquisition_file.py, apiv2/graphql_api/types/gain_file.py, apiv2/graphql_api/types/per_section_alignment_parameters.py, apiv2/graphql_api/types/run.py, apiv2/graphql_api/types/tiltseries.py, apiv2/graphql_api/types/tomogram.py, apiv2/graphql_api/types/tomogram_author.py, apiv2/graphql_api/types/tomogram_voxel_spacing.py, apiv2/platformics/graphql_api/core/query_builder.py, apiv2/template_overrides/graphql_api/types/class_name.py.j2, apiv2/tests/test_aggregate_filters.py
Relates to / fixes [#1417](https://github.com/chanzuckerberg/cryoet-data-portal/issues/1417) and implements filtering on aggregates almost identically to the way that Hasura supports aggregate filters.
=> feat: support filtering on related aggregates

apiv2/Makefile, apiv2/README.md, apiv2/db_import/README.md
=> chore: Docs for apiv2 and importers.

ingestion_tools/scripts/data_validation/README.md, ingestion_tools/scripts/data_validation/allure_tests.py, ingestion_tools/scripts/data_validation/conftest.py, ingestion_tools/scripts/data_validation/tests/annotation/test_instancesegmentation_annotation.py, ingestion_tools/scripts/data_validation/tests/annotation/test_metadata_annotation.py, ingestion_tools/scripts/data_validation/tests/annotation/test_orientedpoint_annotation.py, ingestion_tools/scripts/data_validation/tests/annotation/test_point_annotation.py, ingestion_tools/scripts/data_validation/tests/annotation/test_segmentationmask_annotation.py, ingestion_tools/scripts/data_validation/tests/test_alignments.py, ingestion_tools/scripts/data_validation/tests/test_dataset.py, ingestion_tools/scripts/data_validation/tests/test_frame.py, ingestion_tools/scripts/data_validation/tests/test_gain.py, ingestion_tools/scripts/data_validation/tests/test_neuroglancer.py, ingestion_tools/scripts/data_validation/tests/test_run.py, ingestion_tools/scripts/data_validation/tests/test_tilt_angles.py, ingestion_tools/scripts/data_validation/tests/test_tiltseries.py, ingestion_tools/scripts/data_validation/tests/test_tomogram.py, ingestion_tools/scripts/data_validation/tests/test_voxelspacing.py
Relates to ~
- Adds definition for alignment marker
- Cleans up the usage of pytest namespace for custom values generated for running 
- Adding ability to do local test runs with allure, without syncing to remote s3
- Removes a s3 deletion that is redundant as the asset is replaced
=> chore: Cleans up pytest namespace for data validation

ingestion_tools/scripts/common/fs.py
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1390
Added `setxattr` to S3 ingestion for `ContentType` attribute
=> feat: add content type for s3 ingestion

ingestion_tools/scripts/common/fs.py
This reverts - https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/421
=> revert: content type

.github/workflows/prod-deploy.yaml
https://czi.atlassian.net/browse/CCIE-3911
Relates to
=> chore: remove deprecated tags

ingestion_tools/dataset_configs/deposition_10314.yaml
Relates to N/A
The preprint for the Ais/Pom segmentations is now officially out and should be added to the deposition metadata.
=> feat: Add preprint DOI to annotations and deposition metadata of Ais deposition

.github/workflows/apiv2-test.yml, .github/workflows/argus-stack-prod-upsert.yaml, .github/workflows/argus-stack-rdev-create.yaml, .github/workflows/argus-stack-rdev-delete.yaml, .github/workflows/argus-stack-staging-upsert.yaml, .github/workflows/conventional-commits.yml, .github/workflows/release-please.yaml, .github/workflows/staging-deploy.yaml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
=> fix: Update runs-on labels in GitHub Actions workflows

.github/workflows/workflow-argus-docker-build.yaml
Relates to
Update Argus' Docker Build workflow to use v4.2.0
=> fix: update argus_builder workflow to v4.2.0

apiv2/README.md
=> fix: update to trigger workflow

apiv2/README.md
=> fix: update to trigger workflow 2

.github/workflows/argus-stack-rdev-create.yaml, .github/workflows/docker-build-staging-prod.yaml, .infra/rdev/values.yaml, apiv2/README.md
<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>App Name</th>
<td>cryoet-apiv2</td>
</tr>
<tr>
<th>Stack Name</th>
<td>working-koala</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://working-koala.dev-cryoet.dev.czi.team" target="_blank">https://working-koala.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---
<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>Name</th>
<td>kaloster-apiv2-update</td>
</tr>
<tr>
<th>Short Name</th>
<td>working-koala</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://working-koala.dev-cryoet.dev.czi.team" target="_blank">https://working-koala.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Relates to
=> fix: update staging/prod builder

.github/workflows/docker-build-staging-prod.yaml, .github/workflows/workflow-argus-docker-build.yaml, apiv2/README.md
=> fix: update docker build

.github/workflows/docker-build-staging-prod.yaml, .github/workflows/workflow-argus-docker-build.yaml, apiv2/README.md
=> fix: path_filter formatting

.github/workflows/workflow-argus-docker-build.yaml, apiv2/README.md
=> fix: update argus docker build

ingestion_tools/dataset_configs/deposition_10330.yaml
Relates to N/A
Semantic and Instance segmentations of synaptic vesicles in dataset 10443 created using [SynapseNet](https://www.biorxiv.org/content/10.1101/2024.12.02.626387v1).
=> feat: Ingestion config for synaptic vesicle annotations.

apiv2/db_import/importers/annotation.py, apiv2/db_import/importers/dataset.py, apiv2/db_import/importers/deposition.py, apiv2/db_import/importers/tomogram.py
Relates to https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/433/files
Making new db fields available in the importer.
=> feat: add tag and kaggle id to importers

schema/ingestion_config/v1.0.0/ingestion_config_models_extended.py
Addressing validation failures for ML challenge annotation depositions: https://github.com/chanzuckerberg/cryoet-data-portal-backend/actions/runs/13553802181/job/37883453660?pr=436#step:6:1187
Current config validation checks test if the same type of `AnnotationSourceFile` is used multiple times in the same `sources`-list of an `Annotation`. Under normal circumstances each `sources` list should only contain a maximum of one instance each of: 
- `InstanceSegmentation`
- `OrientedPoint`
- `Point`
- `SegmentationMask`
- `SemanticSegmentationMask`
- `TriangularMesh`
- `TriangularMeshGroup`
However, when `parent_filters` are used to define import locations depending on one of the parent importers, the same type of `AnnotationSourceFile` may actually be present multiple times.
This PR updates …
=> fix: Fix annotation shape validation

ingestion_tools/scripts/data_validation/shared/helper/helper_mrc.py, ingestion_tools/scripts/data_validation/shared/helper/helper_zarr.py, ingestion_tools/scripts/data_validation/shared/helper/mdoc_helper.py, ingestion_tools/scripts/data_validation/shared/helper/tilt_angles_helper.py, ingestion_tools/scripts/data_validation/shared/helper/tiltseries_helper.py, ingestion_tools/scripts/data_validation/shared/util.py, ingestion_tools/scripts/data_validation/source/fixtures/data.py, ingestion_tools/scripts/data_validation/source/test/test_frame.py, ingestion_tools/scripts/data_validation/source/test/test_frame_acquisition_file.py, ingestion_tools/scripts/data_validation/source/test/test_run.py, ingestion_tools/scripts/data_validation/source/test/test_tilt_angles.py, ingestion_tools/scripts/data_validation/source/test/test_tiltseries.py, ingestion_tools/scripts/enqueue_runs.py
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1652
Several fixes for the source validation workflow:
- Fix incorrect fixture caching on EC2 by turning off multiprocessing (the instances are single core anyways)
- Change fixture scopes to make sure the fixtures are cached correctly
- Add `.ali` as an approved file type for tiltseries.
- Add more human readable error messages to the assertions. 
Closes https://github.com/chanzuckerberg/cryoet-data-portal/issues/1652
=> fix: Source data validation fixes.

.infra/prod/Chart.yaml, .infra/rdev/Chart.yaml, .infra/staging/Chart.yaml
https://czi.atlassian.net/browse/CCIE-4211
Bumps the helm chart versions.
=> chore: bump helm chart versions

ingestion_tools/scripts/data_validation/shared/helper/mdoc_helper.py, ingestion_tools/scripts/data_validation/source/README.md, ingestion_tools/scripts/data_validation/source/fixtures/data.py
Relates to
Handles cases where the frame source is default. Treats the list of frame files as an empty list.
=> fix: Handling default frame sources in tests

ingestion_tools/scripts/data_validation/shared/util.py
Relates to N/A
Some tilt series stacks have extension `.mrcs`, added to the list of known formats in the validator.
=> fix: Add another missing alias of MRC format.

ingestion_tools/dataset_configs/10444.yaml
Relates to
Lower case sapiens to be consistent.
=> fix: fix typo in organism name for 10444

apiv2/database/models/dataset.py, apiv2/schema/README.md
Relates to
Updates the README with the latest diagram.
=> fix: adding back schema diagram

apiv2/README.md
Update the database migration documentation with instruction on how to add a table to the ER diagram.
=> chore: Document how to add new table to the ER diagram

apiv2/platformics/graphql_api/core/error_handler.py
This lets our GraphQL API errors return errors when users ask for too many rows from our ListConnections.
=> fix: Add better handling for value error exceptions from pagination.

.github/workflows/workflow-argus-docker-build.yaml
=> feat: update argus docker builder

docs/data_ingestion.md, ingestion_tools/docs/running_data_ingestion.md
- add schema validation as an ingestion step
- Add a link to documention for running validation tests
=> chore: update ingestion steps documentation

ingestion_tools/dataset_configs/10440.yaml, ingestion_tools/dataset_configs/10445.yaml, ingestion_tools/dataset_configs/10446.yaml, ingestion_tools/dataset_configs/10447.yaml, ingestion_tools/dataset_configs/10448.yaml, ingestion_tools/dataset_configs/10449.yaml, ingestion_tools/dataset_configs/10450.yaml, ingestion_tools/dataset_configs/10451.yaml, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.py, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models.schema.json, schema/ingestion_config/v1.0.0/codegen/ingestion_config_models_materialized.yaml, schema/ingestion_config/v1.0.0/ingestion_config_models.yaml
in the ingestion config schema the CTF entity should be plural. This is to maintain consistency with all top level entities in the ingestion config.
=> fix: change ctf to ctfs for the ingest schema.

.github/workflows/argus-stack-prod-upsert.yaml, .github/workflows/argus-stack-rdev-create.yaml, .github/workflows/argus-stack-rdev-delete.yaml, .github/workflows/argus-stack-staging-upsert.yaml
=> fix: update Argus create and delete stack to v0

LICENSE
=> chore: update copywrite

.github/workflows/release-please.yaml
This is an AI generated PR.
Agent: claude_code
Execution time: 14457 ms
Cost: $0.03
=> chore: CCIE-4332 use GH_ACTIONS_HELPER_*

apiv2/README.md
=> feat: Empty commit

release-please-config.json
Relates to ~
This allows the release please branch to be updated for changes that are tagged as chore.
=> chore: Adding chores to changelog
